### ISSUE TITLE
Git segment missing on OS X

### ISSUE THREAD

**Issue by nicooga** [milkbikis/powerline-shell#177]
I'm on OS X 10.10.1, bash.
Git segment missing. Been going crazy about it.
Finally restored it by checking out master~8 (f3c6ff037b5fb7d675ff33b0055906b495d5fadb) and reinstalling.

Ideas?

**Comment by milkbikis** [comment]
I'm not quite sure– does it stop working after that commit?

**Comment by nicooga** [comment]
Yes, in fact, just restoring ´segments/git.py´ to how it looked in that commit (from master, today at 6b3a9108983fde163fa565ffabcecf96af212dd6) removes the issue:

´´´bash
git checkout master
git checkout f3c6ff0 -- segments/git.py
´´´

Here's the diff:
```diff
diff --git a/segments/git.py b/segments/git.py
index 84017a1..1c8b525 100644
--- a/segments/git.py
+++ b/segments/git.py
@@ -6,19 +6,16 @@ def get_git_status():
     has_untracked_files = False
     origin_position = ""
     output = subprocess.Popen(['git', 'status', '--ignore-submodules'],
-            env={"LANG": "C", "HOME": os.getenv("HOME")}, stdout=subprocess.PIPE).communicate()[0]
+                              stdout=subprocess.PIPE).communicate()[0]
     for line in output.split('\n'):
         origin_status = re.findall(
             r"Your branch is (ahead|behind).*?(\d+) comm", line)
-        diverged_status = re.findall(r"and have (\d+) and (\d+) different commits each", line)
         if origin_status:
             origin_position = " %d" % int(origin_status[0][1])
             if origin_status[0][0] == 'behind':
                 origin_position += u'\u21E3'
             if origin_status[0][0] == 'ahead':
                 origin_position += u'\u21E1'
-        if diverged_status:
-            origin_position = " %d%c %d%c" % (int(diverged_status[0][0]), u'\u21E1', int(diverged_status[0][1]), u'\u21E3')

         if line.find('nothing to commit') >= 0:
             has_pending_commits = False
```

**Comment by ecasilla** [comment]
Im having the same issue how did you get it to work?

**Comment by palmerabollo** [comment]
I had this issue on OSX, too.  I had to remove the `env`parameter in the `subprocess.Popen` call, as @nicooga describes in his comment. Otherwise it raises the following exception, failing silently, and not adding the git status:

```python
>>> subprocess.Popen(['git', 'status', '--ignore-submodules'], env={"LANG": "C", "HOME": os.getenv("HOME")}, stdout=subprocess.PIPE).communicate()[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by b-ryan** [comment]
Can anyone confirm whether or not this is still an issue?

**Comment by b-ryan** [comment]
Since I didn't hear back I'm going to close this. There have been considerable changes to the git segment that I would expect to have either fixed this or made the issue present itself differently.
